name: deploy-react-app-to-aws
author: Arky Asmal
description: Deploys a React App to an S3 bucket, and then invalidates the Cloudfront cache for it.
inputs:
  aws_region:
    type: string
    required: true
  aws_access_key_id:
    type: string
    required: true
  aws_secret_access_key:
    type: string
    required: true
  cloudfront_distribution_id:
    type: string
    default: '1'
    required: false
  bucket_name:
    type: string
    required: true
  deployment_url:
    type: string
    default: www.example.com
    required: false
  environment_name:
    type: string
    default: production
    required: false
  react_app_secrets:
    type: string
    default: '{}'
    required: false
jobs:
  Build-App-And-Upload-to-S3:
    environment:
      name: ${{ inputs.environment_name }}
      url: ${{ inputs.deployment_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Extract React App environment variables
        run: aasmal97/create-react-app-env@1.0.0
        with:
          REACT_APP_SECRETS: ${{inputs.react_app_secrets}}
      - name: Build static site
        run: |
          npm install
          npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }} # Use your bucket region here
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://${{ inputs.bucket_name }} --delete
  Invalidate-Cloudfront Cache:
    needs: Build-App-And-Upload-to-S3
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Invalidate Cloudfront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ inputs.cloudfront_distribution_id }}
          PATHS: "/*"
          AWS_REGION: ${{ inputs.aws_region }}
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
