name: "Test Workflow"
on: [push, pull_request]
jobs:
  Test-Workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        aws_region: ${{ secrets.AWS_APP_REGION }}
        aws_access_key_id: ${{ secrets.AWS_S3_DEPLOY_USER_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_S3_DEPLOY_USER_SECRET_KEY }}
        cloudfront_distribution_id: ${{ secrets.AWS_APP_DISTRIBUTION_ID }}
        bucket_name: ${{ secrets.AWS_APP_BUCKET_NAME }}
        react_app_secrets: ${{ toJson(secrets) }}
        node_verison: 16
        path_to_app: ./test-app